// import type { Metadata } from "next";
"use client";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { onAuthStateChanged, User, signOut } from "firebase/auth";
import { auth } from "../firebase/config";
import { FaRegUserCircle } from "react-icons/fa";
import Link from "next/link";
import { Button } from "@/components/ui/button";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<User | null>(null);
  const router = useRouter();
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
        setLoading(false);
      } else {
        router.push("/");
      }
    });
    return () => {
      unsubscribe();
    };
  }, [router]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="h-screen overflow-hidden">
            {/* <Logo /> */}
            <div>
              <header className="h-screen w-64 relative py-6 px-5 border-solid border-2 border-slate-200">
                <h1 className="text-2xl font-bold">Spinshort</h1>
                <div className="flex flex-col mt-10">
                  <Link className="p-4 border-2 mb-2" href="/dashboard">
                    Dashboard
                  </Link>
                  <Link className="p-4 border-2" href="/dashboard/settings">
                    Settings
                  </Link>
                </div>
                <div className="absolute bottom-0 left-0 w-full flex justify-center">
                  <Button
                    className="my-4 mx-4 bg-red-700 mx-auto"
                    onClick={() => signOut(auth)}
                  >
                    Log out
                  </Button>
                </div>
              </header>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto h-screen">
            <main className=" flex justify-between items-center py-3 px-6 border-solid border-2 border-slate-200 sticky top-0 bg-white">
              <nav>
                <h1 className=" font-bold text-base">Dashboard</h1>
              </nav>
              <div className="flex items-center gap-4">
                <Link href="/dashboard/createlink">
                  <Button>Create new link</Button>
                </Link>
                <div className="flex gap-1">
                  <FaRegUserCircle className="text-2xl text-slate-300 cursor-pointer" />
                  <h1 className="text-slate-400">{user?.email}</h1>
                  <h1 className="text-slate-400">{user?.displayName}</h1>
                </div>
              </div>
            </main>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
